### PR TITLE
Added stuff from the one issue.

### PR DESCRIPTION
**Pull request by urbanawakening**
Title.
Was referencing this when I said https://github.com/RicoValdezio/GiganticAmethyst/issues/1 "the one issue"

### CODE REVIEW

**Comment by RicoValdezio** [comment]
I'll take a closer look at this request once I get off work today. Looks good at a glance, but I'll want to clean it up a bit and test it.

**Comment by urbanawakening** [comment]
Pushed more commits that are general code cleanup because I realized the initial one was a complete mess.

**Comment by RicoValdezio** [comment]
Please take a look at the changes I just pushed up and check that it still works for you. If it does, I'll pull and release. I converted the tokens to strings since I couldn't get the tokens to compile. I also removed your comments since the PR will still show them.

**Comment by urbanawakening** [comment]
Saw the changes, they seem good! I realize now why the tokens weren't working was because I forgot to add a submodule dependency on AssetPlus (you have to do that if you want tokens to work properly). Pushed a new commit too. Also in the readme, can you mention me as SushiDev rather than Sushi?

**Comment by RicoValdezio** [comment]
Gladly! I'll go ahead and pull this in, change the mention to SushiDev, and get a release built and uploaded. Thanks for putting this config stuff together!

**Pull request merged**
